version: 3.8.3
timezone: America/Los_Angeles
collections:
  docs:
    permalink: "/:collection/:path/"
    output: true
  posts:
    permalink: "/news/:year/:month/:day/:title/"
    output: true
  tutorials:
    output: true
defaults:
- scope:
    path: _docs
    type: docs
  values:
    layout: docs
- scope:
    path: _posts
    type: posts
  values:
    layout: news_item
    image: "/img/twitter-card.png"
plugins:
- jekyll-avatar
- jekyll-feed
- jekyll-mentions
- jekyll-redirect-from
- jekyll-seo-tag
- jekyll-sitemap
- jemoji
sass:
  style: compressed
exclude:
- ".gitignore"
- CNAME
- icomoon-selection.json
- readme.md
theme: jekyll-theme-minimal
